name: Run action

on: [push]

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - name: Run 3rd party action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Tan
      - name: Logging 3rd party
        run: echo ${{ steps.greet.outputs.time }}