name: Repository events

on:
  push:
    branches: [main, "features/*"]
    tags: [v1.*]
    paths: ['**.ts', '**.js', '**.tsx', '**.jsx']
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

jobs:
  trigger-event:
    name: Repository events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4