name: Trigger event

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

jobs:
  trigger-event:
    name: Trigger event
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: Echo "Hello World"