name: Working directory and shells

on: [push]

defaults:
  run:
    shell: bash

jobs:
  display-ubuntu-working-directory-info:
    name: Display Ubuntu working directory info
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory & list of files
        run: |
          pwd
          ls -a
      - name: Change working directory
        working-directory: /home/runner
        run: |
          pwd
          ls -a

  display-window-working-directory-info:
    name: Display Window working directory info
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display working directory & list of files
        run: |
          Get-Location
          dir
      - name: Python shell
        shell: python
        run: |
          import platform
          print(platform.processor())
