name: Workflow commands
on: [push]

jobs:
  testing-wf-commands:
    name: Testing workflow commands
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting error with parameter
        run: echo "::error title=Error title,file=app.js,line=2::Missing semicolon"
      - name: Setting warning with parameter
        run: echo "::warning title=Warning title,file=app.js,line=2::Missing semicolon"